title: Laravel back-end developer exercise
description: Sample exercise for onboarding new back-end developers in PHP 8 and Laravel 12
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman
